#!/bin/bash
#SBATCH --export=ALL
#SBATCH -N 1
#SBATCH -t 300
#SBATCH --exclusive
#SBATCH --no-requeue
#SBATCH -o bjp8.out
#SBATCH -D /home/pp03008/trab_i
echo bsp-25.8
echo Initial Time is `date`
./bsp-25.8 > ./tmp/bsp-25.8.tmp
echo Final Time is `date`
echo bsp-150.8
echo Initial Time is `date`
./bsp-150.8 > ./tmp/bsp-150.8.tmp
echo Final Time is `date`
echo bsp-500.8
echo Initial Time is `date`
./bsp-500.8 > ./tmp/bsp-500.8.tmp
echo Final Time is `date`